# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Adam Croom"
description: > # this means to ignore newlines until "email:"
   Director of Digital Learning at the University of Oklahoma. A collection of thoughts in my search for "better." Some things are edtech. Some things are not.

email: oucroom@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
blog-logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Adam Croom'
author: 'Adam Croom'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://adamcroom.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/acroom
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	google-plus
    url:	https://plus.google.com/+AdamCroomOK/
    desc: Follow me on Google Plus
    share_url: https://plus.google.com/share?url=http://www.adamcroom.com
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	flickr
    url:	https://www.flickr.com/photos/acroom//
    desc: Follow me on Flickr
    share_url:
    share_title:
    share_link:

  - icon:	youtube
    url:	https://www.youtube.com/channel/UCOyP194ZgeRb9JJoLNS1Wvw
    desc: Follow me on YouTube
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/adamcroom
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
